server:
  port: 9527

spring:
  application:
    name: servercloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-zuul-9527 #仅仅是显示的名称
    prefer-ip-address: true #显示Ip


info:
  app.name: sean-servercloud
  company.name: www.sean.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


zuul:
  prefix: /sean
  ignored-services: "*" # 隐藏的服务名，*代表全部隐藏（servercloud-dept）
  routes: #真实服务名和别名的映射
    mydept.serviceId: servercloud-dept
    mydept.path: /mydept/**



