server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com #服务端实例名
  client:
    register-with-eureka: true #不注册自己
    fetch-registry: true #提供服务，不检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #设置服务地址

